---

# This role contains the common configuration adn prerequisites of the machine

- name: Set The ssh key
  copy: src={{ private_key }} dest=~/.ssh/id_rsa mode=0600
  tags:
    - id_rsa
    - ssh

- name: Install git
  apt: pkg=git
  when: ansible_os_family == "Debian"
  sudo: True
  tags:
    - git